spring.application.name=Warfare Simulation API

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# TODO To test locally without container
spring.datasource.url=jdbc:postgresql://localhost:5432/warfare
spring.datasource.username=postgres
spring.datasource.password=postgres

# TODO Only for tests
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-001-init.xml

server.port=8080
